worker_processes auto;

pid /app/nginx.pid;

events {
    worker_connections 1024;
}

http {
    access_log /app/access.log;
    error_log /app/error.log;

    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    sendfile on;
    keepalive_timeout 65;

    include /etc/nginx/sites-enabled/*;
}